# Generated by Django 4.1 on 2022-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_post_candidates_delete_contesting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="voterlist",
            name="email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
