# Generated by Django 4.1 on 2022-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="candidates",
            field=models.ManyToManyField(to="voting.candidate"),
        ),
        migrations.DeleteModel(
            name="Contesting",
        ),
    ]
